# Generated by Django 5.2.11 on 2026-02-22 05:50

import django.db.models.deletion
import django.utils.timezone
import web.models.character
import web.models.user
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='user/photos/default.png', upload_to=web.models.user.photo_upload_to)),
                ('profile', models.TextField(default='谢谢你的关注', max_length=500)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profile', models.TextField(max_length=100000)),
                ('photo', models.ImageField(upload_to=web.models.character.photo_upload_to)),
                ('background_image', models.ImageField(upload_to=web.models.character.background_image_upload_to)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.userprofile')),
            ],
        ),
    ]
