# Generated by Django 6.0.2 on 2026-03-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='total_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
