# Generated by Django 6.0.2 on 2026-03-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_message_total_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='input',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='message',
            name='output',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='message',
            name='user_message',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
