# Generated by Django 6.0.2 on 2026-03-25 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_voice_character_voice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voice',
            name='description',
        ),
    ]
