# Generated by Django 6.0.2 on 2026-04-04 08:26

import web.models.voice
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_remove_voice_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='local_file',
            field=models.FileField(blank=True, null=True, upload_to=web.models.voice.voice_upload_to),
        ),
    ]
