# Generated by Django 6.0.2 on 2026-04-04 08:31

import django.db.models.deletion
import web.models.voice
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_voice_local_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voice',
            name='local_file',
            field=models.FileField(null=True, upload_to=web.models.voice.voice_upload_to),
        ),
    ]
