# Generated by Django 6.0.2 on 2026-04-06 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_voice_author_alter_voice_local_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='voice',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.voice'),
        ),
    ]
